### ISSUE TITLE
Very slow performance compared to Apache

### ISSUE THREAD

**Issue by toorshia** [learning/SublimeServer#19]
Hi,

I've been happily using sublimeserver with ST2 for quite some time, just came across strange issue.

I am running AngularJS app using server plugin.
Looking at Network tab in Chrome DevTools, here's what it says:
SublimeServer - takes 15s to pull in all local resources.
Apache - takes around 1s. 

In both cases, cache is cleared, so all resources are fresh (which is irrelevant I guess, since everything is local anyway).

Does anyone know what might be the problem?

**Comment by learning** [comment]
multi-thread handler has been added.
