### ISSUE TITLE
server stop/restart in ST3

### ISSUE THREAD

**Issue by snnwolf** [learning/SublimeServer#25]
I have problem (long, long waiting) when try stop/restart Sublime server in ST3 on mac os x 10.10.1

**Comment by hoodwink73** [comment]
I cannot seem to restart the server. ST3 freezes while trying to restart the server.

**Comment by kieranju** [comment]
I get this as well.

**Comment by elimoto** [comment]
Yep, me too.

**Comment by Nashorn** [comment]
Same here.

**Comment by dek1chan** [comment]
Me too.

**Comment by learning** [comment]
This bug fixed in [0.3.3](https://github.com/learning/SublimeServer/releases/tag/0.3.3)
