### ISSUE TITLE
Sublime crashes when stopping the server

### ISSUE THREAD

**Issue by Nashorn** [learning/SublimeServer#28]
I am running Sublime Text 3 with the SublimeServer. The server starts fine, but stopping it will cause Sublime Text to freeze and then crash consistently.

**Comment by Nashorn** [comment]
BTW --- I am on OSX 10.10.3

**Comment by phree** [comment]
Same problem here. I'm on 10.9.5 OSX

**Comment by Daniel-Hug** [comment]
Same issue here on windows 8.1

**Comment by MrliMr** [comment]
same problem here，restarting it also  will cause ST3 to freeze. i'm on OS X  10.11.1.

**Comment by brainz80** [comment]
Same on Windows 10 with Sublime Text 3 build 3083.

**Comment by igor0ser** [comment]
Same problem on Windows 7

**Comment by learning** [comment]
Please track #25
