### ISSUE TITLE
不知道作者你还在吗？这个插件真是超赞，另外能添加一个快捷键吗？

### ISSUE THREAD

**Issue by wmxl** [learning/SublimeServer#37]
用了这个插件抛弃intellij IDEA了，另外作者，view this file on broswer 能添加一个热键吗？ 感觉还是需要的，鼠标操作还是不如键盘来的快。

**Comment by w3c0929** [comment]
`{ "keys":["alt+shift+p"],"command": "sublimeserver_start", "caption": "Start SublimeServer" },
{ "keys":["alt+shift+["],"command": "sublimeserver_stop", "caption": "Stop SublimeServer" },
{ "keys":["alt+shift+]"],"command": "sublimeserver_restart", "caption": "Restart SublimeServer" },`

**Comment by wmxl** [comment]
谢谢， 不过我是菜鸟，这段代码应该放在哪里啊，

**Comment by learning** [comment]
@wmxl 在是在，但是不打算维护了。
不过近期有可能会梳理一下重写一个。

@HeDonglin 说的那个，可以直接放到`Preferences`->`Key Bindings`的设置里

**Comment by wmxl** [comment]
谢谢 搞定了！   这个不需要维护啦！ 已经很好用了！

**Comment by learning** [comment]
@wmxl 谢谢 🤣  我要是写新版本一定告诉你

**Comment by wmxl** [comment]
@learning   哈哈 好的！

**Comment by sergiolin** [comment]
你好，HeDonglin 设置的快捷键是sublimeserver的开启和关闭吧，我想问一下，view in SublimeServer的快捷键怎么设置呢？
{ "keys": ["ctrl+alt+g"], "command": "View in SublimeServer"},
这个无效

**Comment by learning** [comment]
@sergiolin 

```
{ "keys": ["ctrl+alt+g"], "command": "sublimeserver_browser"}
```

**Comment by Qzhor** [comment]
@learning
请问你的command是怎么找到的？我经常装一些插件想要设置快捷键却不知道指令...

**Comment by learning** [comment]
@Qzhor 
`Preferences` -> `Key Bindings`
